---
name: Setup Prolog
author: Yevhen Fabizhevskyi
description: This action sets up Prolog programming language.
branding:
  icon: terminal
  color: gray-dark
inputs:
  force:
    description: |
      If "true" it installs swipl even if it is already installed on a runner.
      Otherwise, skips installation.
    default: "false"
    required: false
outputs:
  installed:
    description: Whether swipl was installed or not.
    value: "${{ steps.install-swipl.outcome == 'success' }}"
runs:
  using: "composite"
  steps:
    - name: Fail
      if: ${{ runner.os == 'Windows' && !contains(fromJSON('["X86", "X64"]'), runner.arch) }}
      run: |
        echo "::error::${RUNNER_OS} ${RUNNER_ARCH} is not supported"
        exit 1
      shell: sh

    - name: Validate inputs
      id: validate-inputs
      env:
        INPUT_FORCE: "${{ inputs.force }}"
      run: ./validate-inputs.sh "${INPUT_FORCE}"
      shell: sh
      working-directory: ${{ github.action_path }}/src

    - name: Collect info
      id: info
      env:
        INPUT_FORCE: "${{ inputs.force }}"
      run: ./collect-info.sh "${INPUT_FORCE}"
      shell: sh
      working-directory: "${{ github.action_path }}/src"

    - name: Install swipl
      if: ${{ steps.info.outputs.bin-installed == 'false' }}
      id: install-swipl
      run: ./${{ runner.os == 'Linux' && 'linux' || (runner.os == 'macOS' && 'macos' || 'windows') }}.sh
      shell: sh
      working-directory: ${{ github.action_path }}/src/install-swipl

    - name: Print version
      run: swipl --version
      shell: sh
